---

- name: create setenv.sh
  template:
    src: bin/setenv.sh.j2
    dest: "{{ jolokia_home }}/current/bin/setenv.sh"
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    mode: 0750
  notify:
    - restart jolokia

- name: configure tomcat - web.xml
  template:
    src: WEB-INF/web.xml.j2
    dest: "{{ jolokia_home }}/current/webapps/jolokia/WEB-INF/web.xml"
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    mode: 0640
  notify:
    - restart jolokia

- name: configure tomcat - server.xml
  template:
    src: conf/server.xml.j2
    dest: "{{ jolokia_home }}/current/conf/server.xml"
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    mode: 0640
  notify:
    - restart jolokia

- name: configure tomcat - tomcat-users.xml
  template:
    src: conf/tomcat-users.xml.j2
    dest: "{{ jolokia_home }}/current/conf/tomcat-users.xml"
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    mode: 0640
  notify:
    - restart jolokia
