---

- name: detect JAVA_HOME
  shell: |
    dirname $(dirname $(readlink -f $(command -v javac)))
  ignore_errors: true
  register: __java_home
  tags:
    - java
    - skip_ansible_lint

- name: setting fact for JAVA_HOME
  set_fact:
    java_home: "{{ __java_home.stdout }}"
  when: __java_home is defined

- name: create setenv.sh
  template:
    src: bin/setenv.sh.j2
    dest: "{{ jolokia_home }}/current/bin/setenv.sh"
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    mode: 0750

- name: configure tomcat - web.xml
  template:
    src: WEB-INF/web.xml.j2
    dest: "{{ jolokia_home }}/current/webapps/jolokia/WEB-INF/web.xml"
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    mode: 0640
  notify:
    - restart jolokia

- name: configure tomcat - server.xml
  template:
    src: conf/server.xml.j2
    dest: "{{ jolokia_home }}/current/conf/server.xml"
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    mode: 0640
  notify:
    - restart jolokia

- name: configure tomcat - tomcat-users.xml
  template:
    src: conf/tomcat-users.xml.j2
    dest: "{{ jolokia_home }}/current/conf/tomcat-users.xml"
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    mode: 0640
  notify:
    - restart jolokia

- name: fix permissions for application home directory  # noqa 301
  command: "{{ item }}"
  args:
    warn: false
  with_items:
    - chown -R {{ jolokia_user }}:{{ jolokia_group }} {{ jolokia_home }}
    - find {{ jolokia_home }} -maxdepth 5 -type d ! -perm 0750 -exec chmod 0750 {} \;
    - find {{ jolokia_home }} -maxdepth 5 -type f ! -perm 0640 -exec chmod 0640 {} \;
    - find {{ jolokia_home }} -maxdepth 5 -type f -name "*.sh" ! -perm 0750 -exec chmod 0750 {} \;
