---

- include_tasks: install_tomcat.yml

- name: check for deployed application
  stat:
    path: "{{ jolokia_home }}/current/webapps/jolokia/META-INF/MANIFEST.MF"
  register: _deployed_application

- block:
    - name: create application directory
      file:
        path: "{{ jolokia_home }}/current/webapps/jolokia"
        state: directory
        owner: "{{ jolokia_user }}"
        group: "{{ jolokia_group }}"
        mode: 0750

    - name: download jolokia application to local folder
      become: false
      get_url:
        url: "{{ jolokia_download_url }}"
        dest: "{{ local_tmp_directory }}/{{ jolokia_file_name }}"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false
      tags:
        - jolokia

    - name: deploy application archiv
      copy:
        src: "{{ local_tmp_directory }}/{{ jolokia_file_name }}"
        dest: "{{ deployment_tmp_directory }}"

    - name: unpack archive
      unarchive:
        src: "{{ deployment_tmp_directory }}/{{ jolokia_file_name }}"
        dest: "{{ jolokia_home }}/current/webapps/jolokia/"
        owner: "{{ jolokia_user }}"
        group: "{{ jolokia_group }}"
        mode: 0750
        copy: false

  when: _deployed_application.stat is defined and not _deployed_application.stat.exists

- name: create systemd service unit
  template:
    src: "init/systemd/jolokia.service.j2"
    dest: "{{ systemd_lib_directory }}/jolokia.service"
    owner: root
    group: root
    mode: 0644
