---

- name: check for unpacked tomcat
  stat:
    path: "{{ jolokia_home }}/apache-tomcat-{{ tomcat_version }}"
  register: _tomcat_unpack

- name: check for deployed application
  stat:
    path: "{{ jolokia_home }}/current/webapps/{{ coremedia_application_name }}/META-INF/MANIFEST.MF"
  register: _deployed_application

- block:

    - name: unpack tomcat binary
      unarchive:
        src: "{{ deployment_tmp_directory }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ jolokia_home }}/"
        owner: "{{ jolokia_user }}"
        group: "{{ jolokia_group }}"
        mode: 0750
        copy: false

    - name: create current link for tomcat
      file:
        src: "{{ jolokia_home }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ jolokia_home }}/current"
        state: link
        force: true
        follow: false
        mode: 0640

    - name: remove default webapps
      file:
        name: "{{ jolokia_home }}/current/webapps/{{ item }}"
        state: absent
      loop:
        - docs
        - examples
        - host-manager
        - manager
        - ROOT

  when: _tomcat_unpack.stat is defined and not _tomcat_unpack.stat.exists
