---

- name: prepare
  ansible.builtin.import_tasks: prepare.yml
  tags:
    - jolokia
    - prepare

- name: install
  ansible.builtin.import_tasks: installation.yml
  tags:
    - jolokia
    - install

- name: configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - jolokia
    - configure

- name: service
  ansible.builtin.import_tasks: service.yml
  tags:
    - jolokia
    - service
