---

- name: Include OS-specific variables.
  include_vars:
    file: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.{{ ansible_lsb.codename | lower }}.yml"
    - "{{ ansible_distribution | lower }}.{{ ansible_lsb.major_release }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "default.yml"

- name: prepare
  import_tasks: prepare.yml
  tags:
    - jolokia
    - prepare

- name: install
  import_tasks: installation.yml
  tags:
    - jolokia
    - install

- name: configure
  import_tasks: configure.yml
  tags:
    - jolokia
    - configure

- name: service
  import_tasks: service.yml
  tags:
    - jolokia
    - service
