---

- name: assert python version
  ansible.builtin.assert:
    that: ansible_python.version.major != 2
    msg: "Sorry, we don't support python 2 anymore!"

- name: include OS specific configuration
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yaml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yaml"
        # eg. redhat / debian
        - "{{ ansible_os_family | lower }}.yaml"
        - default.yaml
      skip: true

- name: update package cache
  ansible.builtin.package:
    update_cache: true

- name: install requirements
  ansible.builtin.package:
    name: "{{ jolokia_dependecies }}"
    state: present

- name: create local temporary path
  delegate_to: localhost
  become: false
  ansible.builtin.file:
    path: "{{ local_tmp_directory }}"
    state: directory
    mode: 0750

- name: create temporary path for deployment artefacts
  ansible.builtin.file:
    path: "{{ deployment_tmp_directory }}"
    state: directory
    mode: 0750

- name: create ansible local facts directory
  ansible.builtin.file:
    dest: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: user and group handling
  when:
    - jolokia_user != "root"
  block:
    - name: create jolokia group
      ansible.builtin.group:
        name: "{{ jolokia_user }}"
        state: present
        system: true

    - name: create jolokia user
      ansible.builtin.user:
        name: "{{ jolokia_user }}"
        groups: "{{ jolokia_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: "{{ jolokia_home }}"

    - name: create jolokia home directory
      ansible.builtin.file:
        path: "{{ jolokia_home }}"
        state: directory
        owner: "{{ jolokia_user }}"
        group: "{{ jolokia_group }}"
        mode: 0750

- name: create application logging directory
  ansible.builtin.file:
    src: "{{ jolokia_home }}/current/logs"
    dest: "/var/log/jolokia"
    state: link
    force: true
    follow: false
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    mode: 0750

- name: merge jolokia configuration between defaults and custom
  ansible.builtin.set_fact:
    jolokia_tomcat: "{{ jolokia_tomcat_defaults | combine(jolokia_tomcat, recursive=True) }}"
    jolokia_systemd: "{{ jolokia_systemd_default | combine(jolokia_systemd, recursive=True) }}"

- name: create logrotate script
  block:
    - name: logrotate configuration directory
      ansible.builtin.file:
        path: "{{ logrotate_conf_dir }}"
        state: directory
        mode: 0750

    - name: remove logrotate config
      ansible.builtin.file:
        path: "{{ logrotate_conf_dir }}/jolokia"
        state: absent
      when:
        - not jolokia_logrotate.enabled

    - name: create logrotate config
      ansible.builtin.template:
        src: jolokia_logrotate.j2
        dest: "{{ logrotate_conf_dir }}/jolokia"
        mode: 0640
      when:
        - jolokia_logrotate.enabled
