---

- name: create local temporary path
  delegate_to: localhost
  become: false
  file:
    path: "{{ local_tmp_directory }}"
    state: directory
    mode: 0750

- name: create temporary path for deployment artefacts
  file:
    path: "{{ deployment_tmp_directory }}"
    state: directory
    mode: 0750

- name: install requirements
  package:
    name: "{{ item }}"
    state: present
  loop:
    - unzip

- name: create ansible local facts directory
  file:
    dest: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create jolokia group
  group:
    name: "{{ jolokia_group }}"
    state: present

- name: create jolokia user
  user:
    name: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    shell: /sbin/nologin
    createhome: true
    comment: jolokia user
    home: "{{ jolokia_home }}"

- name: create jolokia home directory
  file:
    path: "{{ jolokia_home }}"
    state: directory
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    mode: 0750

- name: create application logging directory
  file:
    src: "{{ jolokia_home }}/current/logs"
    dest: "/var/log/jolokia"
    state: link
    force: true
    follow: false
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    mode: 0750

- name: merge jolokia_tomcat configuration between defaults and custom
  set_fact:
    jolokia_tomcat: "{{ jolokia_tomcat_defaults |
      combine( jolokia_tomcat, recursive=True ) }}"

- name: merge jolokia_systemd configuration between defaults and custom
  set_fact:
    jolokia_systemd: "{{ jolokia_systemd_default |
      combine( jolokia_systemd, recursive=True ) }}"

- name: create logrotate script
  block:
    - name: logrotate configuration directory
      file:
        path: "{{ logrotate_conf_dir }}"
        state: directory
        mode: 0750

    - name: remove logrotate config
      file:
        path: "{{ logrotate_conf_dir }}/jolokia"
        state: absent
      when:
        - not jolokia_logrotate.enabled

    - name: create logrotate config
      template:
        src: jolokia_logrotate.j2
        dest: "{{ logrotate_conf_dir }}/jolokia"
        mode: 0640
      when:
        - jolokia_logrotate.enabled
