---

- name: install requirements
  package:
    name: "{{ item }}"
    state: present
  loop:
    - unzip

- name: create ansible local facts directory
  file:
    dest: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create jolokia group
  group:
    name: "{{ jolokia_group }}"
    state: present

- name: create jolokia user
  user:
    name: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    shell: /sbin/nologin
    createhome: true
    comment: jolokia user
    home: "{{ jolokia_home }}"

- name: create jolokia home directory
  file:
    path: "{{ jolokia_home }}"
    state: directory
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    mode: 0750

- name: create application logging directory
  file:
    src: "{{ jolokia_home }}/current/logs"
    dest: "/var/log/jolokia"
    state: link
    force: true
    follow: false
    owner: "{{ jolokia_user }}"
    group: "{{ jolokia_group }}"
    mode: 0750

- name: create local temporary path
  become: false
  file:
    path: "{{ local_tmp_directory }}"
    state: directory
  delegate_to: localhost

- name: create temporary path for deployment artefacts
  file:
    path: "{{ deployment_tmp_directory }}"
    state: directory

# - name: detect installed java
#   block:
#
#     - name: detect JAVA_HOME
#       shell: |
#         java -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home' | awk -F' = ' '{print $2}'
#       ignore_errors: true
#       register: __java_home
#
#     - name: setting fact for JAVA_HOME
#       set_fact:
#         jolokia_java_home: "{{ __java_home.stdout }}"
#       when: __java_home is defined and __java_home.stdout is defined
#
#   when: jolokia_java_home | string | length == 0
